spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
      config:
        server:
          git:
            uri: https://github.com/viveknikam339/config-repo
            default-label: main
            clone-on-start: true
server:
  port: 8888